### ISSUE TITLE
App namn

### ISSUE THREAD

**Issue by RamboFisk** [RamboFisk/mcSoftware-DAT255#11]
Okej så vi behöver ett namn till våran app, om ni har några förslag så skriv gärna dem i kommentarerna. :)

**Comment by MsHax085** [comment]
- Event Finder
- Meetup
- Oggelito

Ska fundera mer :)

**Comment by oscarA1994** [comment]
mcIntegra
mcMeetup
LociRes (fancy latin namn)

**Comment by RamboFisk** [comment]
- häng med
- vad händer
- whats up?

**Comment by RamboFisk** [comment]
Jag gillar mcMeetup!

**Comment by oscarA1994** [comment]
> Den som spar, han har.
Oscar Andersson

**Comment by RamboFisk** [comment]
mcMeetup är namnet som gäller! Sticks and stones..
